:sparkles: listo el default de las imagenes
CattleyaTours/frontend pull request #26
Opened 2020-06-09 05:24 UTC by difcortesgu

2020-06-09 20:41 UTC, mbsuarezg commented
-Agregar el import de sitio en CardSitio
-Imagen de portada que prevalece luego de ser eliminada a la hora de editar

2020-06-09 20:44 UTC, mbsuarezg requested changes
-Faltó el import de sitioContext en CardSitio (?)
-Revisar la imagen que prevalece luego de ser eliminada cuando se edita el sitio

2020-06-09 21:07 UTC, vanesa1102 reviewed
La imagen portada del sitio y publicación no se actualizan después de editar el sitio.

2020-06-10 22:43 UTC, vanesa1102 commented
Al momento de editar y cargar mas de 8 imágenes se sale del editor y me redirige a crear un sitio nuevo

2020-06-11 01:43 UTC, merged